language: go

services:
  - docker

before_install:
  - mkdir bin && mkdir build
  - docker build -t evisong/registrator .
  - docker run -d --name registrator-dev evisong/registrator sh
  - docker ps -a
  - docker cp registrator-dev:/bin/registrator ./bin/

script:
  - COMMIT=`git log -n 1 --pretty=format:'%h'`
  - export VERSION=v`cat ./VERSION`-rev.$COMMIT-build.$TRAVIS_BUILD_NUMBER
  - tar -czvf ./build/registrator-$VERSION.tgz ./bin/registrator
  - docker tag evisong/registrator evisong/registrator:$VERSION

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push evisong/registrator:$VERSION
  - docker push evisong/registrator
  - git config --local user.name "CI-BOT"
  - git tag $VERSION

deploy:
  provider: releases
  api_key: $GITHUB_DEPLOY_TOKEN
  file_glob: true
  file: ./build/*
  skip_cleanup: true
