FROM alpine:3.7
CMD ["/bin/registrator"]

# Cache-able layer
RUN apk --no-cache add -t build-deps build-base go git curl \
	&& apk --no-cache add ca-certificates \
	&& export GOPATH=/go && mkdir -p /go/bin && export PATH=$PATH:/go/bin \
	&& curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

COPY . /go/src/github.com/evisong/registrator
RUN cd /go/src/github.com/evisong/registrator \
	&& export GOPATH=/go && export PATH=$PATH:/go/bin \
	&& git config --global http.https://gopkg.in.followRedirects true \
	&& dep ensure \
	&& dep ensure -add github.com/hashicorp/consul@1.5.1 \
	&& go build -ldflags "-X main.Version=dev" -o /bin/registrator
